# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d9156329278794b93c8f92157fe744193a39170f55687135d3734be76570a4d9e25173ca9a22a216afdfe83ee213e63bd1dee1fc6555bf685815d2937495fb

test:
  secret_key_base: 5dfa1501a42addf3732a99fdde8a48e9ad2285c278bf19e0f632f1e4b65980f28d09e1c8e9ff4228eeac8c6fbb55dcc2dfaa59bd90e8aa7bb573c9da19ce0379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a3d9156329278794b93c8f92157fe744193a39170f55687135d3734be76570a4d9e25173ca9a22a216afdfe83ee213e63bd1dee1fc6555bf685815d2937495fb
